services:
  - type: web
    name: DallmayrERP
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://egbiiizxsqlarqpnzxxs.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
