'use client';

import { useEffect, useMemo, useState } from 'react';
import { PageToolbar } from '@/components/ui/PageToolbar';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { getSupabaseClient } from '@/lib/supabase/client';
import type { Branch } from '@/types/dallmayrerp';

type StockRelation = { stock_name: string | null };
type MovementRow = {
  id: string;
  branch: Branch;
  movement_type: string;
  quantity: number;
  quantity_unit: 'item' | 'box';
  source_location_id: string | null;
  destination_location_id: string | null;
  reference_type: string | null;
  notes: string | null;
  balance_after_items: number | null;
  balance_after_boxes: number | null;
  created_at: string;
  stock_items?: StockRelation | StockRelation[] | null;
};
type LocationRow = { id: string; location_code: string; description: string | null };

function getMovementStockName(row: MovementRow) {
  const relation = row.stock_items;
  if (Array.isArray(relation)) return relation[0]?.stock_name ?? 'Unlinked';
  return relation?.stock_name ?? 'Unlinked';
}

export function InventoryLedgerPanel() {
  const [movements, setMovements] = useState<MovementRow[]>([]);
  const [locations, setLocations] = useState<LocationRow[]>([]);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function loadLedger() {
    setError(null);
    const client = getSupabaseClient();
    const [ledgerResult, locationResult] = await Promise.all([
      client.from('inventory_movements').select('id, branch, movement_type, quantity, quantity_unit, source_location_id, destination_location_id, reference_type, notes, balance_after_items, balance_after_boxes, created_at, stock_items(stock_name)').order('created_at', { ascending: false }).limit(250),
      client.from('stock_locations').select('id, location_code, description').order('location_code'),
    ]);
    const firstError = ledgerResult.error ?? locationResult.error;
    if (firstError) throw firstError;
    setMovements((ledgerResult.data ?? []) as MovementRow[]);
    setLocations((locationResult.data ?? []) as LocationRow[]);
    setLastUpdated(new Date());
  }

  useEffect(() => {
    loadLedger().catch((loadError) => setError(loadError instanceof Error ? loadError.message : 'Could not load inventory ledger.'));
  }, []);

  const locationMap = useMemo(() => new Map(locations.map((location) => [location.id, location])), [locations]);

  return (
    <div className="grid">
      {error ? <div className="error">{error}</div> : null}
      <PageToolbar
        actions={<button className="button secondary" onClick={() => loadLedger().catch((loadError) => setError(loadError instanceof Error ? loadError.message : 'Refresh failed.'))} type="button">Refresh ledger</button>}
        description="Read-only evidence generated by receiving, issuing, picking, adjustments, transfers and cycle counts."
        lastUpdated={lastUpdated}
        title="Inventory movement ledger"
      />
      <div className="table-wrap">
        <table>
          <thead><tr><th>Time</th><th>Stock</th><th>Branch</th><th>Movement</th><th>Quantity</th><th>From</th><th>To</th><th>Balance after</th><th>Reference / notes</th></tr></thead>
          <tbody>{movements.length === 0 ? <tr><td colSpan={9}>No inventory movements yet.</td></tr> : movements.map((row) => <tr key={row.id}><td>{new Date(row.created_at).toLocaleString()}</td><td>{getMovementStockName(row)}</td><td>{row.branch.toUpperCase()}</td><td><StatusBadge value={row.movement_type} /></td><td>{row.quantity > 0 ? '+' : ''}{row.quantity} {row.quantity_unit}</td><td>{row.source_location_id ? locationMap.get(row.source_location_id)?.location_code ?? '-' : '-'}</td><td>{row.destination_location_id ? locationMap.get(row.destination_location_id)?.location_code ?? '-' : '-'}</td><td>{row.balance_after_items ?? '-'} items / {row.balance_after_boxes ?? '-'} boxes</td><td>{row.notes ?? row.reference_type ?? '-'}</td></tr>)}</tbody>
        </table>
      </div>
    </div>
  );
}
