create table if not exists public.telemetry_prepaid_balance_state (
  device_id uuid primary key references public.telemetry_devices(id) on delete cascade,
  carrier text not null default 'Vodacom South Africa',
  ussd_code text not null default '*135*500#',
  remaining_bytes bigint,
  balance_text text,
  query_status text not null default 'unknown',
  last_error text,
  checked_at timestamptz,
  received_at timestamptz,
  request_pending boolean not null default false,
  requested_at timestamptz,
  warning_threshold_bytes bigint not null default 104857600,
  critical_threshold_bytes bigint not null default 26214400,
  check_interval_minutes integer not null default 360,
  stale_after_minutes integer not null default 720,
  updated_at timestamptz not null default now(),
  constraint telemetry_prepaid_balance_remaining_nonnegative check (remaining_bytes is null or remaining_bytes >= 0),
  constraint telemetry_prepaid_balance_status_check check (query_status in ('unknown','ok','parse_failed','unsupported','failed')),
  constraint telemetry_prepaid_balance_thresholds_check check (
    critical_threshold_bytes >= 0 and warning_threshold_bytes > critical_threshold_bytes
  ),
  constraint telemetry_prepaid_balance_interval_check check (check_interval_minutes between 15 and 1440),
  constraint telemetry_prepaid_balance_stale_check check (stale_after_minutes between check_interval_minutes and 10080)
);

create table if not exists public.telemetry_prepaid_balance_history (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.telemetry_devices(id) on delete cascade,
  carrier text not null default 'Vodacom South Africa',
  remaining_bytes bigint,
  balance_text text,
  query_status text not null,
  error_text text,
  checked_at timestamptz not null,
  received_at timestamptz not null default now(),
  constraint telemetry_prepaid_history_remaining_nonnegative check (remaining_bytes is null or remaining_bytes >= 0),
  constraint telemetry_prepaid_history_status_check check (query_status in ('ok','parse_failed','unsupported','failed'))
);

create index if not exists telemetry_prepaid_balance_history_device_checked_idx
  on public.telemetry_prepaid_balance_history (device_id, checked_at desc);

alter table public.telemetry_prepaid_balance_state enable row level security;
alter table public.telemetry_prepaid_balance_history enable row level security;
revoke all on table public.telemetry_prepaid_balance_state from public, anon, authenticated;
revoke all on table public.telemetry_prepaid_balance_history from public, anon, authenticated;
grant select, insert, update, delete on table public.telemetry_prepaid_balance_state to service_role;
grant select, insert, update, delete on table public.telemetry_prepaid_balance_history to service_role;

create or replace function public.record_telemetry_prepaid_balance(
  p_device_id uuid,
  p_remaining_bytes bigint,
  p_balance_text text,
  p_query_status text,
  p_error_text text default null,
  p_checked_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_status text := lower(trim(coalesce(p_query_status, 'failed')));
  v_checked_at timestamptz := coalesce(p_checked_at, now());
  v_balance_text text := nullif(left(trim(coalesce(p_balance_text, '')), 1000), '');
  v_error_text text := nullif(left(trim(coalesce(p_error_text, '')), 500), '');
  v_state public.telemetry_prepaid_balance_state%rowtype;
begin
  if v_status not in ('ok','parse_failed','unsupported','failed') then
    raise exception 'Invalid prepaid balance query status' using errcode = '22023';
  end if;
  if v_status = 'ok' and (p_remaining_bytes is null or p_remaining_bytes < 0) then
    raise exception 'A successful prepaid balance query requires non-negative remaining bytes' using errcode = '22023';
  end if;
  if p_remaining_bytes is not null and p_remaining_bytes < 0 then
    raise exception 'Prepaid balance bytes may not be negative' using errcode = '22023';
  end if;
  if not exists (select 1 from public.telemetry_devices where id = p_device_id) then
    raise exception 'Telemetry device not found' using errcode = '22023';
  end if;

  insert into public.telemetry_prepaid_balance_state (
    device_id, remaining_bytes, balance_text, query_status, last_error,
    checked_at, received_at, request_pending, updated_at
  ) values (
    p_device_id, p_remaining_bytes, v_balance_text, v_status, v_error_text,
    v_checked_at, now(), false, now()
  )
  on conflict (device_id) do update set
    remaining_bytes = case when excluded.query_status = 'ok'
      then excluded.remaining_bytes else public.telemetry_prepaid_balance_state.remaining_bytes end,
    balance_text = coalesce(excluded.balance_text, public.telemetry_prepaid_balance_state.balance_text),
    query_status = excluded.query_status,
    last_error = excluded.last_error,
    checked_at = excluded.checked_at,
    received_at = excluded.received_at,
    request_pending = false,
    updated_at = now()
  returning * into v_state;

  insert into public.telemetry_prepaid_balance_history (
    device_id, carrier, remaining_bytes, balance_text, query_status,
    error_text, checked_at, received_at
  ) values (
    p_device_id, v_state.carrier, p_remaining_bytes, v_balance_text, v_status,
    v_error_text, v_checked_at, now()
  );

  return jsonb_build_object(
    'recorded', true,
    'remaining_bytes', v_state.remaining_bytes,
    'query_status', v_state.query_status,
    'checked_at', v_state.checked_at,
    'warning_threshold_bytes', v_state.warning_threshold_bytes,
    'critical_threshold_bytes', v_state.critical_threshold_bytes
  );
end;
$$;

revoke all on function public.record_telemetry_prepaid_balance(uuid,bigint,text,text,text,timestamptz)
  from public, anon, authenticated;
grant execute on function public.record_telemetry_prepaid_balance(uuid,bigint,text,text,text,timestamptz)
  to service_role;

create or replace function public.get_telemetry_prepaid_balances()
returns table (
  device_id uuid,
  device_code text,
  carrier text,
  ussd_code text,
  remaining_bytes bigint,
  balance_text text,
  query_status text,
  last_error text,
  checked_at timestamptz,
  received_at timestamptz,
  request_pending boolean,
  requested_at timestamptz,
  warning_threshold_bytes bigint,
  critical_threshold_bytes bigint,
  check_interval_minutes integer,
  stale_after_minutes integer,
  next_check_at timestamptz,
  is_stale boolean,
  alert_level text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to view prepaid balances' using errcode = '42501';
  end if;

  return query
  select
    d.id,
    d.device_code,
    coalesce(s.carrier, 'Vodacom South Africa'::text),
    coalesce(s.ussd_code, '*135*500#'::text),
    s.remaining_bytes,
    s.balance_text,
    coalesce(s.query_status, 'unknown'::text),
    s.last_error,
    s.checked_at,
    s.received_at,
    coalesce(s.request_pending, false),
    s.requested_at,
    coalesce(s.warning_threshold_bytes, 104857600::bigint),
    coalesce(s.critical_threshold_bytes, 26214400::bigint),
    coalesce(s.check_interval_minutes, 360),
    coalesce(s.stale_after_minutes, 720),
    case when s.checked_at is null then now()
      else s.checked_at + make_interval(mins => coalesce(s.check_interval_minutes, 360)) end,
    s.checked_at is null
      or s.checked_at + make_interval(mins => coalesce(s.stale_after_minutes, 720)) <= now(),
    case
      when s.checked_at is null then 'unknown'
      when s.checked_at + make_interval(mins => coalesce(s.stale_after_minutes, 720)) <= now() then 'stale'
      when s.query_status <> 'ok' then s.query_status
      when s.remaining_bytes = 0 then 'depleted'
      when s.remaining_bytes <= s.critical_threshold_bytes then 'critical'
      when s.remaining_bytes <= s.warning_threshold_bytes then 'low'
      else 'ok'
    end
  from public.telemetry_devices d
  left join public.telemetry_prepaid_balance_state s on s.device_id = d.id
  order by d.device_code;
end;
$$;

revoke all on function public.get_telemetry_prepaid_balances() from public, anon;
grant execute on function public.get_telemetry_prepaid_balances() to authenticated;

create or replace function public.request_telemetry_prepaid_balance(p_device_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_role text := public.current_app_role();
  v_device_id uuid;
begin
  if coalesce(v_role, '') not in ('admin','operations') then
    raise exception 'Only admin or operations may request a prepaid balance check' using errcode = '42501';
  end if;

  select id into v_device_id
  from public.telemetry_devices
  where device_code = trim(p_device_code) and status = 'active';
  if not found then raise exception 'Active telemetry device not found' using errcode = '22023'; end if;

  insert into public.telemetry_prepaid_balance_state (device_id, request_pending, requested_at, updated_at)
  values (v_device_id, true, now(), now())
  on conflict (device_id) do update set
    request_pending = true,
    requested_at = now(),
    updated_at = now();

  return jsonb_build_object('accepted', true, 'device_id', v_device_id, 'request_pending', true);
end;
$$;

revoke all on function public.request_telemetry_prepaid_balance(text) from public, anon;
grant execute on function public.request_telemetry_prepaid_balance(text) to authenticated;

create or replace function public.set_telemetry_prepaid_balance_control(
  p_device_code text,
  p_warning_megabytes integer,
  p_critical_megabytes integer,
  p_check_interval_minutes integer default 360,
  p_stale_after_minutes integer default 720
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_role text := public.current_app_role();
  v_device_id uuid;
  v_warning_bytes bigint;
  v_critical_bytes bigint;
begin
  if coalesce(v_role, '') not in ('admin','operations') then
    raise exception 'Only admin or operations may configure prepaid balance monitoring' using errcode = '42501';
  end if;
  if p_critical_megabytes < 0 or p_warning_megabytes <= p_critical_megabytes then
    raise exception 'Warning MB must be greater than critical MB, and both must be non-negative' using errcode = '22023';
  end if;
  if p_check_interval_minutes not between 15 and 1440 then
    raise exception 'Check interval must be between 15 and 1440 minutes' using errcode = '22023';
  end if;
  if p_stale_after_minutes not between p_check_interval_minutes and 10080 then
    raise exception 'Stale interval must be at least the check interval and no more than 10080 minutes' using errcode = '22023';
  end if;

  select id into v_device_id from public.telemetry_devices where device_code = trim(p_device_code);
  if not found then raise exception 'Telemetry device not found' using errcode = '22023'; end if;

  v_warning_bytes := p_warning_megabytes::bigint * 1048576;
  v_critical_bytes := p_critical_megabytes::bigint * 1048576;
  insert into public.telemetry_prepaid_balance_state (
    device_id, warning_threshold_bytes, critical_threshold_bytes,
    check_interval_minutes, stale_after_minutes, updated_at
  ) values (
    v_device_id, v_warning_bytes, v_critical_bytes,
    p_check_interval_minutes, p_stale_after_minutes, now()
  )
  on conflict (device_id) do update set
    warning_threshold_bytes = excluded.warning_threshold_bytes,
    critical_threshold_bytes = excluded.critical_threshold_bytes,
    check_interval_minutes = excluded.check_interval_minutes,
    stale_after_minutes = excluded.stale_after_minutes,
    updated_at = now();

  return jsonb_build_object(
    'accepted', true,
    'device_id', v_device_id,
    'warning_threshold_bytes', v_warning_bytes,
    'critical_threshold_bytes', v_critical_bytes,
    'check_interval_minutes', p_check_interval_minutes,
    'stale_after_minutes', p_stale_after_minutes
  );
end;
$$;

revoke all on function public.set_telemetry_prepaid_balance_control(text,integer,integer,integer,integer)
  from public, anon;
grant execute on function public.set_telemetry_prepaid_balance_control(text,integer,integer,integer,integer)
  to authenticated;

notify pgrst, 'reload schema';
